name: Build and Publish image to Docker Hub
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - 'api/Dockerfile'
      - 'front-end-nextjs/Dockerfile'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Generate next release tag
        id: tag
        run: |
          # Get latest existing tag (sorted by version)
          latest_tag=$(git ls-remote --tags origin | grep -o 'refs/tags/v.*' | sed 's#refs/tags/##' | sort -V | tail -n 1)
          latest_tag=${latest_tag:-v0.0.0}

          echo "Latest tag: $latest_tag"

          if [[ "$latest_tag" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            major=${BASH_REMATCH[1]}
            minor=${BASH_REMATCH[2]}
            patch=${BASH_REMATCH[3]}
          else
            major=0
            minor=0
            patch=0
          fi

          # Loop to find next available tag
          while true; do
            patch=$((patch + 1))
            new_tag="v$major.$minor.$patch"
            if ! git ls-remote --tags origin | grep -q "refs/tags/$new_tag$"; then
              break
            fi
          done

          echo "Using new tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

          # Tag and push
          git tag "$new_tag"
          git push origin "$new_tag"

      - name: build image
        run: |
          docker build ./api/ -t 100foldtechnologies/capstone:backend
          docker build ./front-end-nextjs/ -t 100foldtechnologies/capstone:frontend

      - name: push image to docker hub
        run: |
          docker login -u 100foldtechnologies -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push 100foldtechnologies/capstone:backend
          docker push 100foldtechnologies/capstone:frontend
